apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example-deployment
  namespace: app-example
  labels:
    app: app-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-example
  template:
    metadata:
      labels:
        app: app-example
    spec:
      containers:
        - name: app-example
          image: ghcr.io/your-repo/app-example:0.0.6
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: secrets
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              memory: 400Mi
