apiVersion: v1
kind: Service
metadata:
  name: app-example
  namespace: app-example
  labels:
    app: app-example
spec:
  type: ClusterIP
  selector:
    app: app-example
  ports:
    - port: 3000
      targetPort: 3000
